# Generated by Django 5.0.1 on 2024-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sidfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skills",
            name="skill_logo",
        ),
        migrations.AlterField(
            model_name="about",
            name="resume",
            field=models.URLField(blank=True, null=True),
        ),
    ]
